Vagrant.configure("2") do |config|

  config.vm.define "soufe1" do |soufe1|
    soufe1.vm.box = "generic/oracle8"
    soufe1.vbguest.auto_update = false
    soufe1.vm.network "private_network", ip: "192.168.10.123"
    soufe1.vm.hostname = "fe"
    soufe1.vm.provision "ansible" do |ansible|
      ansible.playbook = "../playbook.yml"
      ansible.become = true
    end

#    soufe1.vm.provision "ansible" do |ansible|
#      ansible.playbook = "../playbook.yml"
#      ansible.become = true
#    end

    soufe1.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 1
    end

  end

  config.vm.define "soube1" do |soube1|
    soube1.vm.box = "generic/oracle8"
    soube1.vbguest.auto_update = false
    soube1.vm.hostname = "be"
    soube1.vm.network "private_network", ip: "192.168.10.124"

#    soube1.vm.provision "ansible" do |ansible|
#      ansible.playbook = "../playbook.yml"
#      ansible.become = true
#    end
    
    soube1.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 1
    end

  end

end

