---

- name: Deploy prometheus container
  containers.podman.podman_container:
    name: '{{ prometheus_container.name }}'
    image: '{{ prometheus_container.image }}:{{ prometheus_container.image_tag }}'
    state: '{{ prometheus_container.state }}'
    expose: '{{ prometheus_container.exposed_port }}'
    ports: '{{ prometheus_container.mapped_ports }}'
    network: '{{ podman_network_name }}'
    command:
      - '{{ prometheus_container.extra_command_1 }}'
    volume:
      - '{{ playbook_dir }}/{{ prometheus_container.volume }}'
  register: prometheus_container_return
